/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-south-1',
  aws_cognito_identity_pool_id:
    'ap-south-1:b05cd821-2676-45a9-ad53-b4fcf71cea54',
  aws_cognito_region: 'ap-south-1',
  aws_user_pools_id: 'ap-south-1_9uoXfMy6O',
  aws_user_pools_web_client_id: '1ktkgfnsulvkb7ihibe2sv31mj',
  oauth: {},
  aws_user_files_s3_bucket: 'mobile9cf3b3a40ee2414da4026a179998d89170734-dev',
  aws_user_files_s3_bucket_region: 'ap-south-1',
};

export default awsmobile;
