name: Build Android

on:
  push:
    branches: [stage]

jobs:
  # install-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install yarn dependencies
  #       run: |
  #         yarn install
  #     - name: Run tests
  #       run: |
  #         yarn test

  # Second Job
  build-android:
    # needs: install-and-test // no tests yet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          yarn install
      - name: Generate env file
        run: |
          touch .env
          echo ENVIRONMENT="staging"  >> .env
          echo APOLLO_HOST=${{ secrets.STAGE_APOLLO_HOST }}  >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }}  >> .env
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
