name: Build Android

on:
  push:
    branches: [stage]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      # - name: Run tests
      #   run: |
      #     npm test

    # Second Job
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Generate env file
        run: |
          touch .env
          echo ENVIRONMENT="staging" >> .env
          echo APOLLO_HOST="http://192.168.8.103:4000" >> .env
          echo SENTRY_DSN="https://24d2cbe4b8e74cefba064f62aa3a947d@o468316.ingest.sentry.io/5519270" >> .env
          echo TEST_SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
