name: Build Android

on:
  push:
    branches: [stage]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
        run: |
          npm test
     - name: Run tests

    # Second Job
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
